'''options module'''
CREATE_STATISTICS_INTERVAL = 60 * 5
QUEUE_BROWSING_INTERVAL = 60 * 15
SCRAPPING_INTERVAL_SECONDS = 8 * 60 * 60  # 8 hours
SLEEP_AFTER_SEND = 60 * 60  # 60 minutes # TURNED OFF for now
